version: "2"
services:
  openhr20-daemon:
    restart: unless-stopped
    build:
      context: ./
      args:
        - "TZ=${TZ}"
        - "IMG=${IMG}"
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${WS_PORT}:${WS_PORT}
    volumes:
      - ./:/usr/src/app
    devices:
      - ${OPENHR20_MASTER}:${OPENHR20_MASTER}
