version: "2"
services:
  openhr20-daemon:
    restart: unless-stopped
    build:
      context: ./
      args:
        - "TZ=${TZ}"
        - "BUILD_FROM=python:3.10-alpine"
        - "RUNFILE=run.sh"
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${WS_PORT}:${WS_PORT}
    volumes:
      - ./data:/data
    devices:
      - ${OPENHR20_MASTER}:${OPENHR20_MASTER}
