version: "2"
services:
  openhr20-daemon:
    restart: unless-stopped
    build:
      context: ./
      args:
        - "TZ=${TZ}"
    ports:
      - ${HTTP_PORT}:8020
      - ${WS_PORT}:8021
    volumes:
      - ./data/devices.db:/var/cache/openhr20/devices.db
      - ./data/daemon.conf:/etc/openhr20/daemon.conf
      - ./:/usr/src/app
    devices:
      - ${master}:${master}