version: "2"
services:
  openhr20-daemon:
    restart: unless-stopped
    build: .
    ports:
      - 8020:8020
    volumes:
      - /var/cache/openhr20/devices.db:/var/cache/openhr20/devices.db
      - /etc/openhr20/daemon.conf:/etc/openhr20/daemon.conf
      - ./:/usr/src/app
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0