version: "2"
services:
  openhr20-daemon:
    restart: unless-stopped
    build:
      context: ./
      args:
        - "TZ=${TZ}"
    ports:
      - ${HTTP_PORT}:8020
      - ${WS_PORT}:8021
    volumes:
      - ./:/usr/src/app
    devices:
      - ${OPENHR20_MASTER}:${OPENHR20_MASTER}