#!/usr/bin/env sh

export MQTT_HOST=${MQTT_HOST}
export MQTT_PORT=${MQTT_PORT}
export MQTT_USER=${MQTT_USER}
export MQTT_PASS=${MQTT_PASS}

export OPENHR20_MASTER=${OPENHR20_MASTER}
export OPENHR20_BAUD=${OPENHR20_BAUD}
export OPENHR20_TIMEOUT=${OPENHR20_TIMEOUT}
export OPENHR20_DEBUG=${OPENHR20_DEBUG}
export MQTT_QOS=${MQTT_QOS}
export MQTT_RETAIN=${MQTT_RETAIN}
export MQTT_STATS_TOPIC=${MQTT_STATS_TOPIC}
export MQTT_CMND_TOPIC=${MQTT_CMND_TOPIC}
export MQTT_AVAILABILITY_TOPIC=${MQTT_AVAILABILITY_TOPIC}
export MQTT_MODES_RECEIVE=${MQTT_MODES_RECEIVE}
export MQTT_MODES_PUBLISH=${MQTT_MODES_PUBLISH}
export MQTT_PRESETS_RECEIVE=${MQTT_PRESETS_RECEIVE}
export MQTT_PRESETS_PUBLISH=${MQTT_PRESETS_PUBLISH}
export MQTT_DEBUG=${MQTT_DEBUG}
export HTTP_LISTEN_ADDRESS=${HTTP_LISTEN_ADDRESS}
export HTTP_PORT=${HTTP_PORT}
export HTTP_DEBUG=${HTTP_DEBUG}
export WS_LISTEN_ADDRESS=${WS_LISTEN_ADDRESS}
export WS_SCHEME=${WS_SCHEME}
export WS_HOST=${WS_HOST}
export WS_PORT=${WS_PORT}
export WS_DEBUG=${WS_DEBUG}
export TZ=${TZ}
export DEVICES_FILE=/data/devices.db
export BASE_URL=${BASE_URL}

python /openhr20-daemon/openhr20-daemon/openhr20-daemon.py
